### ISSUE TITLE
Is there any feature for merging document on updates, not discarding other fields?

### ISSUE THREAD

**Issue by musaprg** [Kesin11/Firestore-simple#231]
Hi, thanks for this awesome library.

I'm afraid that I might break some fields in the target document when updating them. I want to treat only fields that must be cared for, but other fields that aren't typed there (but already exists) are deleted if I don't set "merge: true" in the official firebase admin SDK. It would be helpful to add the "merge" option to the current "set" method.

**Comment by Kesin11** [comment]
@musaprg What kind of situation are you afraid to break some fields? I know `merge: true` is useful when updating only some fields in the document but also `update` can do the same behavior.

```typescript
  type User = { // Type of 'users' collection document
    name: string,
    age: number,
    createdAt: Date,
  }

  await firestore.collection('users').doc('alice').update({age: 30})
  // is same as
  await firestore.collection('users').doc('alice').set({ age: 30}, { merge: true })
 // isn't it?
```

**Comment by musaprg** [comment]
Oh, I got it, I thought only "set" can be used for updating the target document. Thanks!
