### ISSUE TITLE
Encoding is not working while updating

### ISSUE THREAD

**Issue by nerikosans** [Kesin11/Firestore-simple#256]
**Describe the bug**
In admin env, the data is not processed through `encode` function while using `Collection.update`.
In result, the sample code in README's `encode/decode` section about setting `updated` field on every update will not work.

**Expected behavior**
The data is processed with `encode` before actual update when `Collection.update` is used.

**Additional context**
Confirmed with v7.0.1.

よろしくお願いいたします。日本語でも大丈夫です。

**Comment by Kesin11** [comment]
Thank you for reporting the bug report. But this behavior is not a bug and I'm sorry to poor documentation.
Please use `set()` instead of `update()` for updating Firestore docoment with `encode`.

----
報告ありがとうございます。残念ながらFirestore-simpleは実装上の制限により、`update()`では`encode()`が実行されません。
この挙動はドキュメントにも書いていなかったので、後ほど加筆したいと思います。

`encode()`を実行しつつFirestoreのドキュメントを更新する場合は代わりに`set()`の方をお使いください。

**Comment by nerikosans** [comment]
Thank you for your response. I understand it's an intended behavior. I would really appreciate it if you cloud give more details about the restriction.

返信ありがとうございます。仕様なのですね。
もしよろしければ、実装上の制限について詳しく教えていただけると大変助かります。

**Comment by Kesin11** [comment]
@nerikosans 
（自分の英語力だと文章を組み立てるのに時間がかかってしまうので日本語で書きます）

`encode`と`decode`は1つ1つのプロパティに対して変換するのではなく、例えば `{ userName: 'alice', userAge: 20 }`を`{ user_name: 'alice', user_age: 20 }`と変換するように、複数のプロパティを含むデータをまとめて変換するように設計しています。
このあたりは[READMEのencode/decodeのサンプルコード](https://github.com/Kesin11/Firestore-simple#encodedecode)を見て頂けると分かるかと思います。

Firestore-simpleでは`fetch`や`add`、`set`は型を厳密に設定しているため、例えば以下のようにUser、UserFirestoreの型を渡してFirestoreSimple.collectionのインスタンスを作った場合には、`add`, `set`の引数と`fetch`の戻り値は必ず全てのプロパティが揃っていることが型のレベルでは保証されます。

```typescript
type User = { userName: string, userAge: Number }
type UserFirestore = { user_name: string, user_age: number }

const userCollection = firestoreSimple.collection<User, UserFirestore>({ ... })
const id = await userCollectoin.add({ userName: 'alice', userAge: 20}) // User型しか受け付けない
await userCollection.fetch(id) // 戻り値の型はUser型（ただし実際はFirestoreのドキュメント次第なのでそれを保証するのは自己責任）
```

このように`add`, `set`, `fetch`だけならば何も問題が無いのですが、問題は`update`です。updateは1つのプロパティだけを選択して更新が可能です。むしろその使い方が一般的だと思います。

1つのプロパティだけ指定した場合に何が問題かというと、`encode`の中の処理を自由に書くことを許してしまっているため、例えば以下のような別のプロパティが他のプロパティに影響を与えるケースにおいて容易にエラーになってしまうのです。

```typescript
const userCollection = firestoreSimple.collection<User, UserFirestore>({
  encode: (user) => {
    return {
      user_name: user.userName,
      user_age: user.userAge,
      // Firestoreに書き込むときに自動的に新しいプロパティを追加するということも可能
      // このケースにおいて、例えばupdate({ userName: 'bob' })という呼び出しを許した場合、userAgeが存在しないのでuser_full_stringを正しく生成できない
      // 今回のようなプロパティを追加するだけではなく、あらゆる処理が`encode`の内部で可能なため書き方次第では容易にエラーになってしまう
      user_full_string: `${user.userName}-${user.userAge}`
    }
  }
})
```

初期の設計が高い自由度を実現できるものだった故に、後から実装した`update`を上手く実装できなくなってしまったとも言えます。そのため自分の決断として、`update`は`encode`を通さず、引数の型はUser型ではなく「UserFirestore型に含まれるプロパティ」という型にすることで、通常のFirestoreの`update`と振る舞いは同じだが型に関しては補助するという立ち位置にしました。

これが`update`に関しての制約なのですが、逆に一部のプロパティだけをFirestoreから取得したい`select`を実装して欲しいという要望について今回のencodeと全く同じような理由でdecodeの実装が難しい、ということを別のpull-reqでも返信していたりしました。
https://github.com/Kesin11/Firestore-simple/issues/225

**Comment by nerikosans** [comment]
大変丁寧にご説明いただきありがとうございます。理解しました。
`updated_on` を自動で付与できるような設計が可能だととても便利なのであると嬉しいところですが、難しいですね...
