### ISSUE TITLE
Simple example usage for web?

### ISSUE THREAD

**Issue by zomars** [Kesin11/Firestore-simple#282]
I's there a simple usage example for the web version? The admin version uses `initializeApp` which is not available in the web version.

Any help is appreciated. 🙏

**Comment by Kesin11** [comment]
Here is web version sample code.
https://github.com/Kesin11/Firestore-simple/blob/master/packages/web/example/basic.ts

This sample uses a little hack for working on Firestore local emulator. If you want to try with real Firestore, just get firestore instance according to [Firestore tutorial document](https://firebase.google.com/docs/firestore/quickstart#web_1) and pass to FirestoreSimple constructor.

```typescript
// Initialize Cloud Firestore through Firebase
firebase.initializeApp({
  apiKey: '### FIREBASE API KEY ###',
  authDomain: '### FIREBASE AUTH DOMAIN ###',
  projectId: '### CLOUD FIRESTORE PROJECT ID ###'
})

const db = firebase.firestore()
const firestoreSimple = new FirestoreSimple(db)
```
